pool/config/routes.rb
Pool::Application.routes.draw do

  controller :home do
    get 'home', to: 'home#all'
    get "home/index"
    get "home/edit"
    get "home/pp"
    get 'home/i'
    get 'home/test'
    get 'home/team'
    get 'home/team_roster'
    
    get   'home/all'
    post  'home/all'
    get   'home/skaters'
    post  'home/skaters'
    get   'home/wingers'
    post  'home/wingers'
    get   'home/centers'
    post  'home/centers'
    get   'home/defenders'
    post  'home/defenders'
    get   'home/goalers'
    post  'home/goalers'
    
    get   'home/skaters_rank'
    post  'home/skaters_rank'
    get   'home/skaters_global'
    post  'home/skaters_global'
    get   'home/wingers_rank'
    post  'home/wingers_rank'
    get   'home/centers_rank'
    post  'home/centers_rank'
    get   'home/defenders_rank'
    post  'home/defenders_rank'
    
    get 'home/pplast'
    get 'home/standings'
    get 'home/draft'
  end
  
  
  resources :players do
    post  'edit_individual', on: :collection
    put   'update_individual', on: :collection
  end

  root 'home#all'

  

end

pool/app/models/player.rb
class Player < ActiveRecord::Base
  
  #POOLERS = ['Math Ally', 'Ben', 'Mark', 'Alain', 'no', 'yes']   poolers + ['no', 'yes']
  POOLERS = ['Math Ally', 'Ben', 'Mark', 'Alain', 'no', 'yes']
  
  COLORS = ['green', 'yellow', 'orange', 'red', 'cyan', 'white']



  validates :name, :points, :goals, :assists, :games, :nhl_points, :nhl_goals, :nhl_assists, :nhl_rank, :position, :salary, :my_rank_global, :my_rank_position,
  presence: true

  validates :points, :goals, :assists, :games, :nhl_points, :nhl_goals, :nhl_assists, :nhl_rank, :salary, :my_rank_global, :my_rank_position,
  numericality: {greater_than_or_equal_to: 0}

  #validates :nhl_rank,
  #uniqueness: true

  validates :position,
  format: { with: /D|C|L|R|G/i, message: 'must be D C L R G' }

  validates :power_play, :pp_last_year,
  allow_blank: true, format: { with: /F1|F2|F3|F4|F5|F6|D1|D2|D3|M|N/, message: 'must be F1 F2 F3 F4 F5 F6 D1 D2 D3 M N' }
    
  #validates :color, inclusion: COLORS
    
  validates :drafted,
  inclusion: POOLERS
    
  validates :my_rank_global,
  numericality: {greater_than_or_equal_to: 1}

  #validate :points_equal_sum_goals_assists, :nhl_points_equal_sum_nhl_goals_nhl_assists



  private

  def points_equal_sum_goals_assists
    errors.add(:points, "total of points different than sum of goals + assists") unless self.points != (self.goals + self.assists) 
  end


  def nhl_points_equal_sum_nhl_goals_nhl_assists
    errors.add(:nhl_points, "total of nhl_points different than sum of nhl_goals + nhl_assists") unless self.nhl_points != (self.nhl_goals + self.nhl_assists)
  end
  
  def pp_already
    if 1
      errors.add(:power_play, "pp rank already picked for this team")
    end
  end


end

pool/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
    
  # GET /players
  # GET /players.json
  def index
    @players = Player.where('season = ?', @year).order('points DESC')
    #@players = Player.where('position = "G" and salary = 0').order('points DESC')
    #@players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end


  #############################
  # DRAFT
  #############################
  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
    def update
      case @mode
      when 'draft'
        respond_to do |format|
          if @player.update(player_params)
            format.html { redirect_to @player, notice: 'Player was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @player.errors, status: :unprocessable_entity }
          end
        end

      
      when 'prep'
    
        puts "Now changing positions (not global) if required"
        if player_params[:my_rank_position].to_i != @player.my_rank_position.to_i
          puts 'rank_actual', @rank_actual = @player.my_rank_position.to_i
          puts 'rank_new', @rank_new = player_params[:my_rank_position].to_i
          puts 'from_what_rank', @from_what_rank = [@rank_actual, @rank_new].min
      
          @players_to_shift = if @player.position == 'L' or @player.position == 'R'
            Player.where("season = ? AND my_rank_position != 9999 AND my_rank_position >= ? AND (position = 'R' OR position = 'L')", \
              @year, @from_what_rank).order('my_rank_position ASC')
          else
            Player.where("season = ? AND my_rank_position != 9999 AND my_rank_position >= ? AND position = ?", \
              @year, @from_what_rank, @player.position).order('my_rank_position ASC  ')
          end
      
          puts 'p count', @players_to_shift.count
          puts 'rank_max', @rank_max = @players_to_shift.maximum(:my_rank_position).to_i
    
          if @rank_new > @rank_actual
            puts 'Start: decrease'
            @i = @rank_actual + 1
            while @i <= @rank_new and @i <= @rank_max
              puts @i
              p = @players_to_shift.where('my_rank_position = ?', @i).take!
              p.my_rank_position = p.my_rank_position - 1
              if p.save
                puts 'A position was decreased with success'
              else
                puts 'A position was NOT decreased with success'
              end
              @i = @i + 1
            end
          elsif @rank_new < @rank_actual and @rank_actual != 9999
            puts 'Start: increase when already ranked'
            @i = @rank_actual - 1
            while @i >= @rank_new
              puts @i
              p = @players_to_shift.where('my_rank_position = ?', @i).take!
              p.my_rank_position = p.my_rank_position + 1
              if p.save
                puts 'A position was increased successfully! (saved in DB)'
              else
                puts 'A position was --NOT-- increased successfully! (not saved in DB)'
              end
              @i = @i - 1
            end
          elsif @rank_new < @rank_actual and @rank_actual == 9999
            puts 'Start: increase when actual 9999'
            @i = @rank_max
            while @i >= @rank_new
              puts @i
              p = @players_to_shift.where('my_rank_position = ?', @i).take!
              p.my_rank_position = p.my_rank_position + 1
              if p.save
                puts 'A position was increased successfully! (saved in DB) when 9999'
              else
                puts 'A position was --NOT-- increased successfully! (not saved in DB) when 9999'
              end
              @i = @i - 1
            end
          end
        end
  

        puts "Now changing positions (global) if required"
        if player_params[:my_rank_global].to_i != @player.my_rank_global.to_i
          puts 'rank_actual', @rank_actual = @player.my_rank_global.to_i
          puts 'rank_new', @rank_new = player_params[:my_rank_global].to_i
          puts 'from_what_rank', @from_what_rank = [@rank_actual, @rank_new].min
      
          @players_to_shift = Player.where("season = ? AND my_rank_global != 9999 AND my_rank_global >= ? AND (position = 'R' OR position = 'L' OR position = 'C' OR position = 'D')", @year, @from_what_rank).order('my_rank_global ASC', 'points DESC')
      
          puts 'p count', @players_to_shift.count
          puts 'rank_max', @rank_max = @players_to_shift.maximum(:my_rank_global).to_i
    
          if @rank_new > @rank_actual
            puts 'Start: decrease'
            @i = @rank_actual + 1
            while @i <= @rank_new and @i <= @rank_max
              puts @i
              p = @players_to_shift.where('my_rank_global = ?', @i).take!
              p.my_rank_global = p.my_rank_global - 1
              if p.save
                puts 'A position was decreased with success'
              else
                puts 'A position was NOT decreased with success'
              end
              @i = @i + 1
            end
          elsif @rank_new < @rank_actual and @rank_actual != 9999
            puts 'Start: increase when already ranked'
            @i = @rank_actual - 1
            while @i >= @rank_new
              puts @i
              p = @players_to_shift.where('my_rank_global = ?', @i).take!
              p.my_rank_global = p.my_rank_global + 1
              if p.save
                puts 'A position was increased successfully! (saved in DB)'
              else
                puts 'A position was --NOT-- increased successfully! (not saved in DB)'
              end
              @i = @i - 1
            end
          elsif @rank_new < @rank_actual and @rank_actual == 9999
            puts 'Start: increase when actual 9999'
            @i = @rank_max
            while @i >= @rank_new
              puts @i
              p = @players_to_shift.where('my_rank_global = ?', @i).take!
              p.my_rank_global = p.my_rank_global + 1
              if p.save
                puts 'A position was increased successfully! (saved in DB) when 9999'
              else
                puts 'A position was --NOT-- increased successfully! (not saved in DB) when 9999'
              end
              @i = @i - 1
            end
          end
        end  
    
    
        puts "Now updating player and redirecting surfer"
        respond_to do |format|
          if @player.update(player_params)
            #format.html { redirect_to @player, notice: 'Player was successfully updated.' }
            format.html { redirect_to session[:return_to], notice: 'Player was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @player.errors, status: :unprocessable_entity }
          end
        end #respond_to
      end #update
    
    end #case @mode
    
    
    

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
  
  
  def edit_individual
    @players = Player.find(params[:player_ids])
  end
  
  
  def update_individual
    @players = Player.update(params[:players].keys, params[:players].values).reject { |p| p.errors.empty? }
    if @players.empty?
      puts 'updated'
      flash[:notice] = "Players updated"
      redirect_to players_path
    else
      puts 'not working'
      flash[:notice] = "Players --NOT-- updated"
      render :action => "edit_individual"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :points, :goals, :assists, :rank, :nhl_points, :nhl_goals, :nhl_assists, :nhl_rank, :team, :last_team, :power_play, :pp_last_year, :position, :salary, :color, :games, :drafted, :season, :my_rank_global, :my_rank_position)
    end
    
end

pool/app/helpers/players_helper.rb
module PlayersHelper
end

pool/app/views/players/_fields.html.erb
<tr>
	<td>
		<div class="field">
			<%= f.number_field :rank %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :name %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :team %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :position %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :power_play %>
		</div>
	</td>	
	<td>
		<div class="field">
			<%= f.text_field :games %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :points %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :nhl_goals %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :nhl_assists %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :salary %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :pp_last_year %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.text_field :color %>
		</div>
	</td>
	<td>
		<div class="field">
			<%= f.number_field :drafted %>
		</div>
	</td>
</tr>

pool/app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
<% if @player.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

	<ul>
		<% @player.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="actions">
	<%= f.submit %>
</div>
<table border='0'>
	<tr>
		<td>
			<div class="field">
				<%= f.label :name %><br>
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label :id %><br>
				<%= f.number_field :id %>
			</div>
			<div class="field">
				<%= f.label :games %><br>
				<%= f.text_field :games %>
			</div>
			<div class="field">
				<%= f.label :points %><br>
				<%= f.number_field :points %>
			</div>
			<div class="field">
				<%= f.label :goals %><br>
				<%= f.number_field :goals %>
			</div>
			<div class="field">
				<%= f.label :assists %><br>
				<%= f.number_field :assists %>
			</div>
			<div class="field">
				<%= f.label :rank %><br>
				<%= f.number_field :rank %>
			</div>
			<div class="field">
				<%= f.label :nhl_points %><br>
				<%= f.number_field :nhl_points %>
			</div>
			<div class="field">
				<%= f.label :nhl_goals %><br>
				<%= f.number_field :nhl_goals %>
			</div>
			<div class="field">
				<%= f.label :nhl_assists %><br>
				<%= f.number_field :nhl_assists %>
			</div>
			<div class="field">
				<%= f.label :nhl_rank %><br>
				<%= f.number_field :nhl_rank %>
			</div>
		</td>
		<td>
			<div class="field">
				<%= f.label :team %><br>
				<%= f.text_field :team %>
			</div>
			<div class="field">
				<%= f.label :last_team %><br>
				<%= f.text_field :last_team %>
			</div>
			<div class="field">
				<%= f.label :power_play %><br>
				<%= f.text_field :power_play %>
			</div>
			<div class="field">
				<%= f.label :pp_last_year %><br>
				<%= f.text_field :pp_last_year %>
			</div>
			<div class="field">
				<%= f.label :my_rank_position %><br>
				<%= f.number_field :my_rank_position %>
			</div>
			<div class="field">
				<%= f.label :my_rank_global %><br>
				<%= f.number_field :my_rank_global %>
			</div>
			<div class="field">
				<%= f.label :position %><br>
				<%= f.text_field :position %>
			</div>
			<div class="field">
				<%= f.label :salary %><br>
				<%= f.number_field :salary %>
			</div>
			<div class="field">
				<%= f.label :color %><br>
				<%= f.select :color, Player::COLORS %>
			</div>
			<div class="field">
				<%= f.label :drafted %><br>
				<%= f.select :drafted, Player::POOLERS %>
			</div>
			<div class="field">
				<%= f.label :season %><br>
				<%= f.text_field :season %>
			</div>
		</td>
	</tr>
</table>
<% end %>

pool/app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

pool/app/views/players/edit_individual.html.erb
<p><h2>Edit multiple</h2></p>

<%= form_tag update_individual_players_path, method: :put do %>
	<table>
		<thead>
			<tr>
				<th>Rank</th>
				<th>Name</th>
				<th>Team</th>
				<th>Position</th>
				<th>Power play</th>
				<th>Games</th>
				<th>Points</th>
				<th>Goals</th>
				<th>Assists</th>
				<th>Salary</th>
				<th>Last PP</th>
				<th>Color</th>
				<th>Drafted</th>
				<th></th>
			</tr>
		</thead>
		
		<tbody>
			<% @players.each do |player| %>
				<%= fields_for "players[]", player do |f| %>
					<%= render "fields", :f => f %>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<p><%= submit_tag "Submit" %></p>
<% end %>		

pool/app/views/players/index.html.erb
<h1>Listing players</h1>

<p><%= link_to 'New Player', new_player_path %></p>

<%= form_tag edit_individual_players_path do %>

	<p><%= submit_tag "Edit checked" %></p>

	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Games</th>
				<th>Points</th>
				<th>Goals</th>
				<th>Assists</th>
				<th>Rank</th>
				<th>Nhl points</th>
				<th>Nhl goals</th>
				<th>Nhl assists</th>
				<th>Nhl rank</th>
				<th>Team</th>
				<th>Last team</th>
				<th>Power play</th>
				<th>Pp last year</th>
				<th>Position</th>
				<th>Salary</th>
				<th>Color</th>
				<th>Drafted</th>
				<th>Season</th>
				<th>Rank position</th>
				<th>Rank global</th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @players.each do |player| %>
			<tr style='background-color:<%=player.color%>'>
				<td><%= player.name %></td>
				<td><%= player.games %></td>
				<td><%= player.points %></td>
				<td><%= player.goals %></td>
				<td><%= player.assists %></td>
				<td><%= player.rank %></td>
				<td><%= player.nhl_points %></td>
				<td><%= player.nhl_goals %></td>
				<td><%= player.nhl_assists %></td>
				<td><%= player.nhl_rank %></td>
				<td><%= player.team %></td>
				<td><%= player.last_team %></td>
				<td><%= player.power_play %></td>
				<td><%= player.pp_last_year %></td>
				<td><%= player.position %></td>
				<td><%= number_to_currency player.salary, precision: 0 %></td>
				<td><%= player.color %></td>
				<td><%= player.drafted %></td>
				<td><%= player.season %></td>
				<td><%= player.my_rank_position %></td>
				<td><%= player.my_rank_global %></td>
				<td><%= check_box_tag "player_ids[]", player.id %></td>
				<td><%= link_to 'Show', player %></td>
				<td><%= link_to 'Edit', edit_player_path(player) %></td>
				<td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	
<% end %>

pool/app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

pool/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Id (auto):</strong>
  <%= @player.id %>
</p>

<p>
  <strong>Games:</strong>
  <%= @player.games %>
</p>

<p>
  <strong>Points:</strong>
  <%= @player.points %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @player.goals %>
</p>

<p>
  <strong>Assists:</strong>
  <%= @player.assists %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @player.rank %>
</p>

<p>
  <strong>Nhl points:</strong>
  <%= @player.nhl_points %>
</p>

<p>
  <strong>Nhl goals:</strong>
  <%= @player.nhl_goals %>
</p>

<p>
  <strong>Nhl assists:</strong>
  <%= @player.nhl_assists %>
</p>

<p>
  <strong>Nhl rank:</strong>
  <%= @player.nhl_rank %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team %>
</p>

<p>
  <strong>Last team:</strong>
  <%= @player.last_team %>
</p>

<p>
  <strong>Power play:</strong>
  <%= @player.power_play %>
</p>

<p>
  <strong>Pp last year:</strong>
  <%= @player.pp_last_year %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>

<p>
  <strong>Salary:</strong>
  <%= number_to_currency @player.salary, precision: 0 %>
</p>

<p>
  <strong>Color:</strong>
  <%= @player.color %>
</p>

<p>
  <strong>Drafted:</strong>
  <%= @player.drafted %>
</p>

<p>
  <strong>Rank position:</strong>
  <%= @player.my_rank_position %>
</p>

<p>
  <strong>Rank global:</strong>
  <%= @player.my_rank_global %>
</p>

<p>
  <strong>Season:</strong>
  <%= @player.season %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>